---
#-------------------------------
# General Site Settings
title: doriwon
logo: logo_full.png # You can add own logo.
description: Doriwon's Blog

#-------------------------------
# Author Settings
author:
  name: Nomir Nos
  image: dori.png
  say-hello: Hello, I’m <strong>doriwon</strong>
  bio: Welcome to <strong>Web Pulisher <a href="https://doriwon.github.io/">Doriwon</a></strong>'s Blog

#-------------------------------
# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/son1won/ # Add your Instagram handle
github: https://github.com/doriwon/
# pinterest: https://pinterest.com/ # Add your Pinterest handle

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: dori # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
